model_type: logistic_regression
C: 1.0
max_iter: 300
solver: lbfgs
features:
  - route_id
  - direction_id
  - stop_id
  - time_point_id
  - time_point_order
  - point_type
  - standard_type
  - scheduled_headway
  - day_of_week
  - hour
  - minute_of_day
